### ISSUE TITLE
does inv_table hold all index data in memory?

### ISSUE THREAD

**Issue by yitian134** [SeSaMe-NUS/genie#2]
I've read the inv_table briefly，it seems that inv_table hold all index data in memory? 
If I have a very huge index，is there any way I use the engine.

**Comment by koallen** [comment]
Currently all index data are held in memory. If you index is too large, you can run GENIE on multiple nodes https://github.com/SeSaMe-NUS/genie#multi-node-multi-gpu-example.

**Comment by yitian134** [comment]
thank you for your reply. If it can support disk storage，things will go better~
